# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7bf9f367b8d6aa4ad555efc6c262f01d4e8974504ccccfb0ef79b8d7ec662a9c3b226f073f441b57b59396f73389bd1dc771f7b200244a72e9d589420116c5c8

test:
  secret_key_base: b62852e5852d9d401748b5205041b5caa9bafbdf140ccfdf7bd43a38e6bdea3ef0460a7b679c56723cee8ac8a8b3ec1053c2c612ed0f43374d66f151d0e1a0e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
